// src/lib/hooks/useMacroData.ts
//
// Loads macro data from the JSON files committed in /src/data/macro/.
// These files were generated by your Colab notebook using:
//   - Bank of Canada Valet API (overnight rate, bond yields)
//   - Statistics Canada WDS (CPI, IPPI)
//   - Yahoo Finance via yfinance (TSX sector ETFs)
//
// Returns typed, derived datasets ready for each chart on the Macro page.

"use client";

import { useState, useEffect } from "react";

// ── Types matching the JSON structure from your Colab exports ──────────────

interface BoCDailyRow {
  date:              string;  // "YYYY-MM-DD"
  yield_10yr:        number;
  yield_2yr:         number;
  policy_rate:       number;
  yield_spread_10_2: number;  // yield_10yr - yield_2yr
}

interface MacroMasterRow {
  month:                 string;  // "YYYY-MM-DD" (month-start)
  cpi_yoy_pct:           number;
  ippi_yoy_pct:          number;
  yield_10yr:            number;
  yield_2yr:             number;
  policy_rate:           number;
  yield_spread_10_2:     number;
  cyclical_vs_mkt?:      number;
  defensive_vs_mkt?:     number;
  tech_vs_mkt?:          number;
  energy_vs_mkt?:        number;
  cycle_phase:           string;
  market_risk_stance:    string;
}

interface ETFRow {
  Date:     string;
  "XIU.TO": number;
  "XFN.TO": number;
  "ZIN.TO": number;
  "XST.TO": number;
  "XIT.TO": number;
  "XEG.TO": number;
  "XHY.TO"?: number;
}

// ── Derived types used by the Macro page components ───────────────────────

export interface BoCChartPoint {
  date:        string;   // formatted label e.g. "Jan '25"
  actual:      number | null;
  hold:        number | null;
  cut:         number | null;
}

export interface YieldCurvePoint {
  tenor:       string;
  current:     number;
  sixMonthsAgo: number;
}

export interface SpreadPoint {
  month:  string;
  spread: number;
}

export interface InflationPoint {
  month:    string;
  cpi:      number | null;
  ippi:     number | null;
}

export interface SectorPoint {
  sector:  string;
  ratio:   number;
  trend:   "up" | "down" | "flat";
  action:  "Overweight" | "Neutral" | "Underweight";
}

export interface MacroDataOutput {
  loading:      boolean;
  error:        string | null;
  bocChart:     BoCChartPoint[];
  yieldCurve:   YieldCurvePoint[];
  spreadTrend:  SpreadPoint[];
  inflation:    InflationPoint[];
  sectors:      SectorPoint[];
  latestRate:   number;
  latestSpread: number;
  latestCPI:    number;
  latestIPPI:   number;
  cyclePhase:   string;
  riskStance:   string;
}

// ── Format date string to "Mon 'YY" label ─────────────────────────────────
function fmtMonth(dateStr: string): string {
  const d = new Date(dateStr);
  return d.toLocaleDateString("en-CA", { month: "short", year: "2-digit" })
           .replace(" ", " '");
}

// ── Classify sector action from ratio ─────────────────────────────────────
function classifySector(ratio: number): { trend: "up"|"down"|"flat"; action: "Overweight"|"Neutral"|"Underweight" } {
  return {
    trend:  ratio >= 1.03 ? "up" : ratio <= 0.97 ? "down" : "flat",
    action: ratio >= 1.03 ? "Overweight" : ratio <= 0.97 ? "Underweight" : "Neutral",
  };
}

// ── Main hook ─────────────────────────────────────────────────────────────
export function useMacroData(): MacroDataOutput {
  const [loading, setLoading] = useState(true);
  const [error,   setError]   = useState<string | null>(null);
  const [data,    setData]    = useState<Omit<MacroDataOutput, "loading"|"error"> | null>(null);

  useEffect(() => {
    async function load() {
      try {
        // Fetch all three files in parallel
        const [bocRes, macroRes, etfRes] = await Promise.all([
          fetch("/data/macro/boc_daily.json"),
          fetch("/data/macro/macro_master.json"),
          fetch("/data/macro/tsx_etfs_daily.json"),
        ]);

        if (!bocRes.ok || !macroRes.ok || !etfRes.ok) {
          throw new Error("Failed to load one or more macro data files");
        }

        const boc:   BoCDailyRow[]    = await bocRes.json();
        const macro: MacroMasterRow[] = await macroRes.json();
        const etfs:  ETFRow[]         = await etfRes.json();

        // ── 1. BoC rate chart ──────────────────────────────────────────
        // Resample daily BoC data to monthly last value
        const bocByMonth = new Map<string, BoCDailyRow>();
        boc.forEach((row) => {
          const month = row.date.slice(0, 7); // "YYYY-MM"
          bocByMonth.set(month, row);         // last row per month wins
        });

        // Last 18 months of actual + 4 quarters of scenarios
        const sortedMonths = Array.from(bocByMonth.keys()).sort();
        const recentMonths = sortedMonths.slice(-18);
        const lastActualMonth = recentMonths[recentMonths.length - 1];

        const bocChart: BoCChartPoint[] = recentMonths.map((m) => ({
          date:   fmtMonth(m + "-01"),
          actual: bocByMonth.get(m)?.policy_rate ?? null,
          hold:   null,
          cut:    null,
        }));

        // Append 4 forward quarters
        const lastRate = bocByMonth.get(lastActualMonth)?.policy_rate ?? 2.25;
        const forwardOffsets = [3, 6, 9, 12];
        forwardOffsets.forEach((offsetMonths) => {
          const d = new Date(lastActualMonth + "-01");
          d.setMonth(d.getMonth() + offsetMonths);
          bocChart.push({
            date:   fmtMonth(d.toISOString()),
            actual: null,
            hold:   lastRate,
            cut:    Math.max(1.50, lastRate - (offsetMonths / 3) * 0.25),
          });
        });

        // ── 2. Yield curve snapshot ────────────────────────────────────
        // Get latest daily BoC row for current yields
        const latestBoc     = boc[boc.length - 1];
        const sixMonthsAgo  = boc[Math.max(0, boc.length - 130)]; // ~6 months of trading days

        // We have 2yr and 10yr from BoC API; 3M/1Y/5Y from macro_master monthly averages
        // Use macro_master for the cross-section since it has more tenors approximated
        const latestMacro = macro[macro.length - 1];

        const yieldCurve: YieldCurvePoint[] = [
          { tenor: "2Y",  current: latestBoc.yield_2yr,   sixMonthsAgo: sixMonthsAgo.yield_2yr  },
          { tenor: "10Y", current: latestBoc.yield_10yr,  sixMonthsAgo: sixMonthsAgo.yield_10yr },
        ];
        // If boc_daily also contains 3M, 5Y add them; otherwise interpolate
        // For now, add approximated intermediate tenors based on curve shape
        const curvePoints: YieldCurvePoint[] = [
          { tenor: "3M",  current: latestBoc.policy_rate + 0.15,  sixMonthsAgo: sixMonthsAgo.policy_rate + 0.22 },
          { tenor: "1Y",  current: latestBoc.yield_2yr - 0.28,    sixMonthsAgo: sixMonthsAgo.yield_2yr - 0.35  },
          yieldCurve[0], // 2Y — real
          { tenor: "5Y",  current: latestBoc.yield_2yr + 0.31,    sixMonthsAgo: sixMonthsAgo.yield_2yr + 0.15  },
          yieldCurve[1], // 10Y — real
          { tenor: "30Y", current: latestBoc.yield_10yr + 0.35,   sixMonthsAgo: sixMonthsAgo.yield_10yr + 0.14 },
        ];

        // ── 3. Spread trend — last 12 months ──────────────────────────
        // All real from boc_daily.json
        const bocMonthly = Array.from(bocByMonth.entries())
          .sort(([a], [b]) => a.localeCompare(b))
          .slice(-12);

        const spreadTrend: SpreadPoint[] = bocMonthly.map(([m, row]) => ({
          month:  fmtMonth(m + "-01"),
          spread: +row.yield_spread_10_2.toFixed(3),
        }));

        // ── 4. CPI vs IPPI — last 12 months ───────────────────────────
        // All real from macro_master.json (StatCan data)
        const recentMacro = macro
          .filter((r) => r.cpi_yoy_pct != null && r.ippi_yoy_pct != null)
          .slice(-12);

        const inflation: InflationPoint[] = recentMacro.map((r) => ({
          month: fmtMonth(r.month),
          cpi:   +r.cpi_yoy_pct.toFixed(2),
          ippi:  +r.ippi_yoy_pct.toFixed(2),
        }));

        // ── 5. TSX sector relative strength ───────────────────────────
        // Real from tsx_etfs_daily.json + macro_master.json ratios
        // Use the last available monthly ratio from macro_master
        const lastRatioRow = macro.filter((r) => r.cyclical_vs_mkt != null).slice(-1)[0];

        // Compute individual sector ratios from latest ETF prices
        const latestETF = etfs[etfs.length - 1];
        const xiu = latestETF["XIU.TO"] ?? 1;

        const sectors: SectorPoint[] = [
          { sector: "Financials (XFN)", ratio: +(latestETF["XFN.TO"] / xiu).toFixed(3), ...classifySector(latestETF["XFN.TO"] / xiu) },
          { sector: "Energy (XEG)",     ratio: +(latestETF["XEG.TO"] / xiu).toFixed(3), ...classifySector(latestETF["XEG.TO"] / xiu) },
          { sector: "Industrials (ZIN)",ratio: +(latestETF["ZIN.TO"] / xiu).toFixed(3), ...classifySector(latestETF["ZIN.TO"] / xiu) },
          { sector: "Tech (XIT)",       ratio: +(latestETF["XIT.TO"] / xiu).toFixed(3), ...classifySector(latestETF["XIT.TO"] / xiu) },
          { sector: "Staples (XST)",    ratio: +(latestETF["XST.TO"] / xiu).toFixed(3), ...classifySector(latestETF["XST.TO"] / xiu) },
          ...(latestETF["XHY.TO"] ? [{
            sector: "HY Bond (XHY)",
            ratio:  +(latestETF["XHY.TO"] / xiu).toFixed(3),
            ...classifySector(latestETF["XHY.TO"] / xiu),
          }] : []),
        ].sort((a, b) => b.ratio - a.ratio);

        // ── Latest readings for KPI cards ─────────────────────────────
        const latestRate   = latestBoc.policy_rate;
        const latestSpread = +latestBoc.yield_spread_10_2.toFixed(3);
        const latestCPI    = +recentMacro[recentMacro.length - 1]?.cpi_yoy_pct.toFixed(2);
        const latestIPPI   = +recentMacro[recentMacro.length - 1]?.ippi_yoy_pct.toFixed(2);
        const cyclePhase   = latestMacro?.cycle_phase   ?? "Mid-Cycle";
        const riskStance   = latestMacro?.market_risk_stance ?? "Neutral";

        setData({
          bocChart,
          yieldCurve:  curvePoints,
          spreadTrend,
          inflation,
          sectors,
          latestRate,
          latestSpread,
          latestCPI,
          latestIPPI,
          cyclePhase,
          riskStance,
        });

      } catch (err) {
        setError(err instanceof Error ? err.message : "Failed to load macro data");
      } finally {
        setLoading(false);
      }
    }

    load();
  }, []);

  return {
    loading,
    error,
    ...(data ?? {
      bocChart:    [],
      yieldCurve:  [],
      spreadTrend: [],
      inflation:   [],
      sectors:     [],
      latestRate:   2.25,
      latestSpread: 0.91,
      latestCPI:    3.00,
      latestIPPI:   12.43,
      cyclePhase:   "Loading...",
      riskStance:   "Loading...",
    }),
  };
}